title: Rahmat Agung Julians
email: rahmatagungj@gmail.com
description: >- 
  Rahmat Agung Julians
baseurl: ""
url: "" 
twitter_username: rahmatagungj
github_username:  rahmatagungj

remote_theme: riggraz/no-style-please
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-pwa-workbox

permalink: /:slug

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/


timezone: Asia/Jakarta


pwa:
  sw_src_filepath: service-worker.js # Optional
  sw_dest_filename: service-worker.js # Optional
  dest_js_directory: assets/js # Required
  precache_recent_posts_num: 5 # Optional
  precache_glob_directory: / # Optional
  precache_glob_patterns: # Optional
    - "/**/*.{js,json,css}"
    - "/**/*.{ico,jpg,jpeg,png,svg}"
    - "/**/*.html"
  precache_glob_ignores: # Optional
    - "sw-register.js"
    - "fonts/**/*"
