title: Rahmat Agung Julians
email: rahmatagungj@gmail.com
description: >- 
  Technology Enthusiast | Philosophy | Logic
baseurl: ""
url: "https://rahmatagungjulians.tech" 
twitter_username: Rahmat_A_J
github_username:  rahmatagungj

plugins:
  - jekyll-feed
  - jekyll-sitemap

markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false
    syntax_highlighter: rouge

highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false
      start_line: 1

permalink: /blog/:slug

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - README.md
  - webpack.config.js
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - build/
  - node_modules/
  - src/
  - _draft/
  - documentation/


timezone: Asia/Jakarta


compress_html:
  clippings: [div, p, ul, td, h1, h2]
  comments: ["<!-- ", " -->"]
  endings: [p, li, td]
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: [html, head, body]

defaults:
  -
    scope:
      path:            "assets/**"
    values:
      sitemap:         false