title: Rahmat Agung Julians
email: rahmatagungj@gmail.com
description: >- 
  Technology Enthusiast | Philosophy | Logic
baseurl: ""
url: "" 
twitter_username: Rahmat_A_J
github_username:  rahmatagungj

plugins:
  - jekyll-feed
  - jekyll-sitemap

markdown: kramdown

highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false
      start_line: 1


permalink: /:slug

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/


timezone: Asia/Jakarta
