title: Rahmat Agung Julians
email: rahmatagungj@gmail.com
description: >- 
  Rahmat Agung Julians
#baseurl: ""
url: "" 
twitter_username: rahmatagungj
github_username:  rahmatagungj

remote_theme: riggraz/no-style-please
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  
permalink: /:slug

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/


timezone: Asia/Jakarta
