name: Tests

on:
  push:
    branches:
      - main

jobs:
  github-pages:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-\
    - uses: ./
      with:
        provider: 'github'
        token: ${{ secrets.GH_TOKEN }}
        jekyll_src: './'
